services:
  web:
    environment:
      DJANGO_ALLOWED_HOSTS: "fashionexpress.ciphertextlabs.com,.ciphertextlabs.com,localhost,127.0.0.1"
      DJANGO_CSRF_TRUSTED_ORIGINS: "https://fashionexpress.ciphertextlabs.com,https://*.ciphertextlabs.com"

